"""Shared utilities for Unicode table generation."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.request
from dataclasses import dataclass
from functools import cache
from typing import Callable, Iterable, IO

UNICODE_VERSION = "17.0.0"

NUM_CODEPOINTS = sys.maxunicode + 1

BYTE_BITS = 8
BYTE_SIZE = 1 << BYTE_BITS
BYTE_MASK = BYTE_SIZE - 1

FILE_HEADER = "// Generated by scripts/generate.py -- DO NOT EDIT\n"

Codepoint = int

_cache_dir: str | None = None
_emitted_files: list[str] = []


@dataclass(frozen=True)
class UnicodeRecord:
    codepoint: Codepoint
    name: str
    general_category: str
    canonical_combining_class: int
    bidi_class: str
    decomposition_type: str | None
    decomposition: tuple[Codepoint, ...]


def get_cache_dir() -> str:
    """Return (and lazily create) a temporary directory for downloaded Unicode data files."""
    global _cache_dir
    if _cache_dir is None:
        _cache_dir = os.path.join(tempfile.gettempdir(), f"unicode-data-{UNICODE_VERSION}")
        os.makedirs(_cache_dir, exist_ok=True)
    return _cache_dir


def fetch_open(filename: str, emoji: bool = False):
    """Opens ``filename``, downloading it from unicode.org if not cached."""
    basename = os.path.basename(filename)
    localname = os.path.join(get_cache_dir(), basename)
    if not os.path.exists(localname):
        prefix = "emoji" if emoji else "ucd"
        url = f"https://www.unicode.org/Public/{UNICODE_VERSION}/{prefix}/{filename}"
        print(f"  Downloading {url} ...")
        urllib.request.urlretrieve(url, localname)
    try:
        return open(localname, encoding="utf-8")
    except OSError:
        sys.stderr.write(f"cannot load {localname}")
        sys.exit(1)


def load_unicode_version() -> tuple[int, int, int]:
    with fetch_open("ReadMe.txt") as readme:
        pattern = r"for Version (\d+)\.(\d+)\.(\d+) of the Unicode"
        return tuple(map(int, re.search(pattern, readme.read()).groups()))  # type: ignore


def load_property(filename: str, pattern: str, action: Callable[[int], None]):
    regex = re.compile(pattern)
    for low, high, value in iter_property_entries(filename):
        if regex.fullmatch(value):
            for cp in range(low, high + 1):
                action(cp)


def to_sorted_ranges(codepoints: Iterable[Codepoint]) -> list[tuple[Codepoint, Codepoint]]:
    """Collapse an iterable of codepoints into a sorted list of inclusive ranges."""
    lst = sorted(codepoints)
    ret: list[tuple[Codepoint, Codepoint]] = []
    for cp in lst:
        if ret and ret[-1][1] == cp - 1:
            ret[-1] = (ret[-1][0], cp)
        else:
            ret.append((cp, cp))
    return ret


def emit_cangjie_file(path: str, generator: Callable[[IO[str]], None]):
    """Write a generated Cangjie source file with a standard header."""
    if os.path.exists(path):
        os.remove(path)
    with open(path, "w", newline="\n", encoding="utf-8") as f:
        f.write(FILE_HEADER)
        generator(f)
    _emitted_files.append(path)


def format_emitted_files():
    """Run cjfmt on all files written by emit_cangjie_file(), if available."""
    if not _emitted_files:
        return
    if not shutil.which("cjfmt"):
        print("  Warning: cjfmt not found, skipping formatting")
        return
    print(f"\n=== Formatting {len(_emitted_files)} generated file(s) ===")
    for path in _emitted_files:
        normalized = os.path.normpath(path)
        subprocess.run(f"cjfmt -f {normalized}", shell=True, check=True, capture_output=True)
        print(f'  Formatted "{normalized}"')


@cache
def load_unicode_data() -> dict[Codepoint, UnicodeRecord]:
    records: dict[Codepoint, UnicodeRecord] = {}
    with fetch_open("UnicodeData.txt") as udata:
        for line in udata:
            line = line.strip()
            if not line:
                continue
            fields = line.split(";")
            codepoint = int(fields[0], 16)
            name = fields[1]
            decomposition_field = fields[5]
            decomposition_type: str | None = None
            decomposition: tuple[Codepoint, ...] = ()
            if decomposition_field:
                raw_parts = decomposition_field.split()
                if raw_parts[0].startswith("<") and raw_parts[0].endswith(">"):
                    decomposition_type = raw_parts[0][1:-1]
                    raw_parts = raw_parts[1:]
                decomposition = tuple(int(part, 16) for part in raw_parts)
            records[codepoint] = UnicodeRecord(
                codepoint=codepoint,
                name=name,
                general_category=fields[2],
                canonical_combining_class=int(fields[3]),
                bidi_class=fields[4],
                decomposition_type=decomposition_type,
                decomposition=decomposition,
            )
    return records


@cache
def load_name_map() -> dict[str, Codepoint]:
    name_map: dict[str, Codepoint] = {}
    for record in load_unicode_data().values():
        if not record.name.startswith("<"):
            name_map[record.name] = record.codepoint
    with fetch_open("NameAliases.txt") as aliases:
        for line in aliases:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            codepoint_text, alias, _alias_type = [part.strip() for part in line.split(";")]
            name_map[alias] = int(codepoint_text, 16)
    return name_map


def find_codepoint(name: str) -> Codepoint:
    return load_name_map()[name]


def find_codepoints_by_name_regex(pattern: str) -> set[Codepoint]:
    regex = re.compile(pattern)
    return {
        record.codepoint
        for record in load_unicode_data().values()
        if not record.name.startswith("<") and regex.search(record.name)
    }


def find_codepoints_with_canonical_decomposition(
    decomposition: tuple[Codepoint, ...],
) -> set[Codepoint]:
    return {
        record.codepoint
        for record in load_unicode_data().values()
        if record.decomposition_type is None and record.decomposition == decomposition
    }


def find_codepoints_with_canonical_decomposition_suffix(
    suffix: tuple[Codepoint, ...],
) -> set[Codepoint]:
    return {
        record.codepoint
        for record in load_unicode_data().values()
        if record.decomposition_type is None
        and len(record.decomposition) >= len(suffix)
        and record.decomposition[-len(suffix) :] == suffix
    }


def find_codepoints_with_canonical_decomposition_prefix(
    prefix: tuple[Codepoint, ...],
) -> set[Codepoint]:
    return {
        record.codepoint
        for record in load_unicode_data().values()
        if record.decomposition_type is None
        and len(record.decomposition) >= len(prefix)
        and record.decomposition[: len(prefix)] == prefix
    }


def find_codepoints_by_predicate(predicate: Callable[[UnicodeRecord], bool]) -> set[Codepoint]:
    return {
        record.codepoint
        for record in load_unicode_data().values()
        if predicate(record)
    }


@cache
def iter_property_entries(filename: str) -> tuple[tuple[int, int, str], ...]:
    entries: list[tuple[int, int, str]] = []
    with fetch_open(filename) as properties:
        for line in properties:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            range_text, value = [part.strip() for part in line.split(";", 1)]
            if ".." in range_text:
                low_text, high_text = range_text.split("..", 1)
            else:
                low_text = range_text
                high_text = range_text
            entries.append((int(low_text, 16), int(high_text, 16), value))
    return tuple(entries)


@cache
def load_property_map(filename: str) -> dict[str, set[Codepoint]]:
    property_map: dict[str, set[Codepoint]] = {}
    for low, high, value in iter_property_entries(filename):
        prop_set = property_map.setdefault(value, set())
        prop_set.update(range(low, high + 1))
    return property_map


def load_property_set(filename: str, value: str) -> set[Codepoint]:
    return set(load_property_map(filename).get(value, set()))


@cache
def load_blocks() -> dict[str, list[tuple[Codepoint, Codepoint]]]:
    blocks: dict[str, list[tuple[Codepoint, Codepoint]]] = {}
    for low, high, block_name in iter_property_entries("Blocks.txt"):
        blocks.setdefault(block_name, []).append((low, high))
    return blocks


def codepoints_for_block(block_name: str) -> set[Codepoint]:
    codepoints: set[Codepoint] = set()
    for low, high in load_blocks()[block_name]:
        codepoints.update(range(low, high + 1))
    return codepoints
