"""Shared utilities for Unicode table generation."""

import os
import re
import sys
import tempfile
import urllib.request
from typing import Callable, Iterable, IO

UNICODE_VERSION = "17.0.0"

NUM_CODEPOINTS = 0x110000

FILE_HEADER = "// Generated by scripts/generate.py -- DO NOT EDIT\n"

Codepoint = int

_cache_dir: str | None = None


def get_cache_dir() -> str:
    """Return (and lazily create) a temporary directory for downloaded Unicode data files."""
    global _cache_dir
    if _cache_dir is None:
        _cache_dir = os.path.join(tempfile.gettempdir(), f"unicode-data-{UNICODE_VERSION}")
        os.makedirs(_cache_dir, exist_ok=True)
    return _cache_dir


def fetch_open(filename: str, emoji: bool = False):
    """Opens ``filename``, downloading it from unicode.org if not cached."""
    basename = os.path.basename(filename)
    localname = os.path.join(get_cache_dir(), basename)
    if not os.path.exists(localname):
        prefix = "emoji" if emoji else "ucd"
        url = f"https://www.unicode.org/Public/{UNICODE_VERSION}/{prefix}/{filename}"
        print(f"  Downloading {url} ...")
        urllib.request.urlretrieve(url, localname)
    try:
        return open(localname, encoding="utf-8")
    except OSError:
        sys.stderr.write(f"cannot load {localname}")
        sys.exit(1)


def load_unicode_version() -> tuple[int, int, int]:
    with fetch_open("ReadMe.txt") as readme:
        pattern = r"for Version (\d+)\.(\d+)\.(\d+) of the Unicode"
        return tuple(map(int, re.search(pattern, readme.read()).groups()))  # type: ignore


def load_property(filename: str, pattern: str, action: Callable[[int], None]):
    with fetch_open(filename) as properties:
        single = re.compile(rf"^([0-9A-F]+)\s*;\s*{pattern}\s+")
        multiple = re.compile(rf"^([0-9A-F]+)\.\.([0-9A-F]+)\s*;\s*{pattern}\s+")

        for line in properties.readlines():
            raw_data = None
            if match := single.match(line):
                raw_data = (match.group(1), match.group(1))
            elif match := multiple.match(line):
                raw_data = (match.group(1), match.group(2))
            else:
                continue
            low = int(raw_data[0], 16)
            high = int(raw_data[1], 16)
            for cp in range(low, high + 1):
                action(cp)


def to_sorted_ranges(iter: Iterable[Codepoint]) -> list[tuple[Codepoint, Codepoint]]:
    """Collapse an iterable of codepoints into a sorted list of inclusive ranges."""
    lst = sorted(iter)
    ret: list[tuple[Codepoint, Codepoint]] = []
    for cp in lst:
        if ret and ret[-1][1] == cp - 1:
            ret[-1] = (ret[-1][0], cp)
        else:
            ret.append((cp, cp))
    return ret


def emit_cangjie_file(path: str, generator: Callable[[IO[str]], None]):
    """Write a generated Cangjie source file with a standard header."""
    if os.path.exists(path):
        os.remove(path)
    with open(path, "w", newline="\n", encoding="utf-8") as f:
        f.write(FILE_HEADER)
        generator(f)
